import { DepartmentObstetrics } from '@/types/department';
import { Procedure } from '@/types/medical-care-template';

// 産科による処置
export const proceduresByObstetrics: Procedure[] = [
  // CPA覚知/初動
  {
    label: '初動対応（CPA発生）',
    details: 'スタッフから緊急コール',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: '呼吸',
    details: '一つでも異常と感じたら医師コール/心停止の前兆疑い',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: '脈拍',
    details: '一つでも異常と感じたら医師コール/心停止の前兆疑い',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: '意識障害',
    details: '一つでも異常と感じたら医師コール/心停止の前兆疑い',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: 'CPA宣言',
    details: '医師が宣言',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: 'CPR開始',
    details: '発見現場で開始',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: 'コードブルー宣言',
    details: '',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: 'モニター装着',
    details: '血圧、心電図、SP02',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  {
    label: '背版挿入',
    details: '余裕がない場合は不要',
    department: DepartmentObstetrics,
    phase: 'CPA覚知/初動',
  },
  // PMCD想定緊急連絡
  {
    label: 'PMCD実施判断',
    details: '妊婦心肺停止の発生5分経過してROSCしない場合PMCDを実施する',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: '産婦人科他医師コール',
    details: '多数をコール 呼べるだけ',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: 'NICU医師コール',
    details: '75217',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: 'CCMCコール',
    details: '77777',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: '手術室麻酔科コール',
    details: '74325',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: '手術室師長(orリーダー)コール',
    details: '75025(師長) 75155(リーダー)',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: '循環器内科コール',
    details: '74025',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: 'MEセンターコール',
    details: '産科医師/スタッフ(助産師/看護師)',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  {
    label: '家族への連絡',
    details: '空いているスタッフ',
    department: DepartmentObstetrics,
    phase: 'PMCD想定緊急連絡',
  },
  // 蘇生準備/実施
  {
    label: '緊急カート準備',
    details: 'BVM,アドレナリン',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: 'CTG除去',
    details: '胎児モニター不要',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: 'AED準備',
    details: '',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: 'コマンダー変更',
    details: '産科→ICU医師へ変更',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: '末梢ルート確保',
    details: '',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: '細胞外液全開投与',
    details: 'ルート無い場合、誰かが緊急確保',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: '子宮左方移動',
    details: '主に助産師、産科医師',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: 'BVM開始、CPR継続',
    details: '',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: '気管挿管',
    details: '原則CCMC医師に行ってもらう',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  {
    label: 'アドレナリン1mg iv',
    details: '4分間隔',
    department: DepartmentObstetrics,
    phase: '蘇生準備/実施',
  },
  // PMCD準備
  {
    label: '手術申し込み',
    details: 'コマンダー以外が入力する',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: '緊急時汎用同意書取得',
    details: '現在作成中、家族から取得',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: '輸血オーダー',
    details: 'RCC10単位、FFP10単位（最低量）PC20単位（必要時）余裕ない場合事後または手術麻酔科依頼',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'ROSC確認',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'ROSC 無→PMCD宣言',
    details: '産科医師、CCMC医師どちらかが行う',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'ROSC有',
    details: 'PMCD不要宣言。NRFS、子癇はgradeA帝王切開',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'PMCD確定コール',
    details: 'PMCDに向けて動く',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'PMCD決定、実施のコール',
    details: '手術決定',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: '産婦人科他医師コール',
    details: '手術確定コール（病棟に依頼）',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'NICU医師コール',
    details: '手術確定コール 75217',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: 'CCMCコール',
    details: '77777',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: '手術室麻酔科コール',
    details: '手術確定コール 74325',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  {
    label: '手術室師長コール or リーダーコール',
    details: '手術確定コール 75025 or 75155',
    department: DepartmentObstetrics,
    phase: 'PMCD準備',
  },
  // PMCD実施
  {
    label: 'CPR継続 ストレッチャー準備',
    details: 'A6病棟→4階手術室',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: 'ストレッチャー移動',
    details: '分娩台のまま移動（分娩室に限定）',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '蘇生処置',
    details: 'CPR継続、AED継続',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '手術室へ移動',
    details: '原則9番手術室',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '仰臥位',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '最低限の清潔処置',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: 'ドレーピング',
    details: '麻酔不要',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: 'PMCD開始宣言',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '胎児娩出',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '児をNICUに渡す',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: '帝王切開終了',
    details: '',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
  {
    label: 'ROSC確認 有/無',
    details: '有→CCMC収容。無→PCPS導入検討→PCPS導入プロトコル',
    department: DepartmentObstetrics,
    phase: 'PMCD実施',
  },
];
